config/routes.rb
Rails.application.routes.draw do
  root "games#index"
  get "predictions", to: "predictions#index", as: :predictions
  get "rankings", to: "rankings#index", as: :rankings
  post "games/:game_id/select_team", to: "games#select_team", as: "select_team"
  resources :games, only: [ :index ] do
    post "select_team", on: :member
  end
  post "submit_predictions", to: "predictions#submit", as: :submit_predictions
  post "set_timezone", to: "users#set_timezone"
  post "games/update_statuses", to: "games#update_statuses"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :predictions

  STATUSES = %w[scheduled inprogress completed final].freeze

  # def start_time_in_central
  #   start_time.in_time_zone("America/Chicago")
  # end

  def self.today_games
    where(start_time: Date.current.all_day)
  end

  def update_game_outcome(api_data)
    # Extract the game result status correctly from the API data
    game_result = api_data.dig("boxscore", "form", 0, "events", 0, "gameResult")

    # Determine the new status based on the game result
    new_status = case game_result
    when "W", "L", "D"
                   "completed"  # Adjust status based on the result (Win, Loss, Draw)
    else
                   "inprogress"
    end

    # Update the status of the game
    self.status = new_status

    # Determine the winning team if applicable
    winner_data = game_result
    if winner_data == "W" || winner_data == "L"
      self.winning_team = api_data.dig("boxscore", "form", 0, "team", "displayName")
    elsif winner_data == "D"
      self.winning_team = "Draw"  # Set the winning team to "Draw" if the game ended in a draw
    end

    # Save the updates to the game record
    save!
  rescue StandardError => e
    Rails.logger.error "Failed to update game outcome for game #{id}: #{e.message}"
  end

  def self.map_api_status(api_status)
    case api_status.downcase
    when "scheduled"
      "scheduled"
    when "inprogress", "status_inprogress"
      "inprogress"
    when "completed", "status_final", "final"
      "completed"
    else
      "scheduled" # Default to scheduled if unknown
    end
  end
end

app/models/prediction.rb
class Prediction < ApplicationRecord
  belongs_to :user
  belongs_to :game

  CONFIDENCE_GAINS = { guessing: 1, hopeful: 2, certain: 3 }
  CONFIDENCE_LOSSES = { guessing: 0, hopeful: -2, certain: -4 }

  def calculate_score
    if game.completed? && game.winning_team == predicted_winner
      self.points_awarded = CONFIDENCE_GAINS[confidence_level.to_sym]
    else
      self.points_awarded = CONFIDENCE_LOSSES[confidence_level.to_sym]
    end
    save
  end
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :user
end

app/models/season_score.rb
class SeasonScore < ApplicationRecord
  belongs_to :user
end

app/models/sport.rb
class Sport < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :predictions
  has_one :score, class_name: "Score"
  has_many :weekly_scores
  has_many :season_scores

  # Fetch the most recent weekly score
  def latest_weekly_score
    weekly_scores.order("week_end DESC").first&.score || 0
  end

  # Fetch the most recent season score
  def latest_season_score
    season_scores.order("season_end DESC").first&.score || 0
  end

  # Fetch the total lifetime score
  def lifetime_score
    score&.total_score
  end

  def predicted?(game)
    predictions.exists?(game_id: game.id)
  end

  # Fetch the user's prediction for a given game
  def prediction_for(game)
    predictions.find_by(game_id: game.id)&.predicted_winner
  end

  def confidence_for(game)
    predictions.find_by(game_id: game.id)&.confidence_level
  end

  # Fetch weekly rankings
  def self.weekly_rankings
    select("users.*, MAX(weekly_scores.score) AS weekly_score")
      .joins(:weekly_scores)
      .group("users.id")
      .order("weekly_score DESC")
  end

  # Fetch season rankings
  def self.season_rankings
    select("users.*, MAX(season_scores.score) AS season_score")
      .joins(:season_scores)
      .group("users.id")
      .order("season_score DESC")
  end

  # Fetch lifetime rankings
  def self.lifetime_rankings
    select("users.*, COALESCE(MAX(scores.total_score), 0) AS lifetime_score")
      .left_joins(:score)
      .group("users.id")
      .order("lifetime_score DESC")
  end

  # Highlight current user in rankings
  def highlight_current_user?(current_user)
    self == current_user
  end
end

app/models/weekly_score.rb
class WeeklyScore < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :set_sports
  protect_from_forgery with: :exception

  private

  def set_sports
    # Load all sports or handle cases where there might be none
    @sports = Sport.all
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!
  # before_action :update_game_statuses
  def index
    @sports = Sport.all
    @current_sport = params[:sport] || @sports.first&.abbreviation
    @games = Game.today_games.where(sport: @current_sport) if @current_sport
    @weekly_score = current_user.latest_weekly_score
    @season_score = current_user.latest_season_score
    @lifetime_score = current_user.lifetime_score
  end

  def update_game_statuses
    # This will update the status of all games that should be in progress
    Game.where(status: "scheduled").where("start_time <= ?", Time.current).update_all(status: "inprogress")
    head :ok
  end

  def update_statuses
    # Logic to update statuses of games
    Game.where(status: "scheduled").where("start_time <= ?", Time.current).update_all(status: "inprogress")
    render json: { message: "Statuses updated" }
  end

  def select_team
    respond_to do |format|
      format.html { redirect_to games_path, notice: "Team selected." }
      format.js
      format.json { render json: { message: "Team selected successfully" }, status: :ok }
    end
  rescue StandardError => e

    respond_to do |format|
      format.html { redirect_to games_path, alert: "Error selecting team." }
      format.json { render json: { error: e.message }, status: :unprocessable_entity }
    end
  end
end

app/controllers/predictions_controller.rb
class PredictionsController < ApplicationController
  def index
    @predictions = current_user.predictions
  end

  def submit
    # Ensure params[:games] exists and is not nil
    if params[:games].present?
      params[:games].each do |game_id, prediction_data|
        game = Game.find(game_id)
        prediction = current_user.predictions.find_or_initialize_by(game: game)
        prediction.update(
          predicted_winner: prediction_data[:team],
          confidence_level: prediction_data[:confidence]
        )
      end
      redirect_to root_path, notice: "Predictions submitted successfully!"
    else
      redirect_to root_path, alert: "No games were selected for prediction."
    end
  end
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
  def index
    @weekly_rankings = User.weekly_rankings
    @season_rankings = User.season_rankings
    @lifetime_rankings = User.lifetime_rankings
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def set_timezone
    session[:timezone] = params[:timezone]
    head :ok
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.erb
<div class="sport-selector" style="overflow-x: scroll; display: flex;">
  <% @sports.each do |sport| %>
    <%= link_to games_path(sport: sport.abbreviation), class: 'sport-item' do %>
      <%= image_tag sport.logo_url, alt: sport.name %>
      <%= sport.abbreviation %>
    <% end %>
  <% end %>
</div>

<h2>Today's <%= @current_sport %> Games!</h2>
<p>
  Your <span class="game-time" data-utc-time="<%= Time.current.iso8601 %>">
    <%= Time.current.strftime('%b %d %Y, %l:%M%P, %Z') %>
  </span>
</p>

<%= form_with url: submit_predictions_path, method: :post, remote: true do %>
  <% @games.each do |game| %>
    <div class="game-block" data-game-id="<%= game.id %>">
      <hr class="game-divider">
      <div class="team-names-wrapper">
      <h3 class="team-names"><%= game.home_team %></h3> vs <h3 class="team-names"><%= game.away_team %></h3>
      </div>
      <% user_timezone = session[:timezone] || 'UTC' %>
      <p>Start Time: <%= game.start_time.in_time_zone(user_timezone).strftime('%b %d %Y, %l:%M%P %Z') %></p>

      <% if game.status == 'inprogress' %>
        <p>You selected <%= current_user.prediction_for(game) %> and you're <%= current_user.confidence_for(game) %> they will win. Good luck!</p>
        <p>The game is in progress. You cannot change your prediction.</p>
      <% elsif current_user.predicted?(game) %>
        <p>You selected <%= current_user.prediction_for(game) %> and you're <%= current_user.confidence_for(game) %> they will win. Good luck!</p>
        <p>Change your mind? There's still time to change your prediction.</p>
        <div class="team-selectors">
          <!-- Note the input names to properly nest game IDs -->
          <%= radio_button_tag "games[#{game.id}][team]", game.home_team %>
          <%= label_tag "games_#{game.id}_team_#{game.home_team}", game.home_team %>
          <%= radio_button_tag "games[#{game.id}][team]", game.away_team %>
          <%= label_tag "games_#{game.id}_team_#{game.away_team}", game.away_team %>
        </div>
        <%= select_tag "games[#{game.id}][confidence]", options_for_select(["Guessing", "Hopeful", "Certain"]) %>
      <% else %>
        <p>Choose your team!</p>
        <div class="team-selectors">
          <!-- Note the input names to properly nest game IDs -->
          <%= radio_button_tag "games[#{game.id}][team]", game.home_team %>
          <%= label_tag "games_#{game.id}_team_#{game.home_team}", game.home_team %>
          <%= radio_button_tag "games[#{game.id}][team]", game.away_team %>
          <%= label_tag "games_#{game.id}_team_#{game.away_team}", game.away_team %>
        </div>
        <%= select_tag "games[#{game.id}][confidence]", options_for_select(["Guessing", "Hopeful", "Certain"]) %>
      <% end %>
    </div>
  <% end %>

  <%= submit_tag 'Submit Predictions', class: 'submit-btn' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Gallywagger" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
     
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script>
      console.log("Page is starting to load...");
      document.addEventListener("DOMContentLoaded", () => {
        console.log("DOMContentLoaded from the application.html.erb head script");

        const csrfToken = document.querySelector('[name=csrf-token]');
        if (csrfToken) {
          console.log("CSRF Token found:", csrfToken.content);
        } else {
          console.error("CSRF Token not found!");
        }

        const timezoneInput = document.createElement("input");
        timezoneInput.type = "hidden";
        timezoneInput.name = "user_timezone";
        timezoneInput.value = Intl.DateTimeFormat().resolvedOptions().timeZone;
        document.body.appendChild(timezoneInput);

        console.log("Sending timezone info:", timezoneInput.value);

        // Send timezone info to the server
        fetch('/set_timezone', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'X-CSRF-Token': document.querySelector('[name=csrf-token]').content
          },
          body: JSON.stringify({ timezone: timezoneInput.value })
        })
        .then(response => {
          if (response.ok) {
            console.log("Timezone successfully sent to the server.");
          } else {
            console.error("Failed to send timezone to the server.");
          }
        })
        .catch(error => {
          console.error("Error during fetch:", error);
        });
      });
    </script>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "timezone_conversion", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar">
        <ul>
            <li><%= link_to 'HOME', root_path %></li>
            <li><%= link_to 'PREDICTIONS', predictions_path %></li>
            <li><%= link_to 'RANKINGS', rankings_path %></li>
            <li><%= link_to current_user ? 'LOGOUT' : 'LOGIN', current_user ? destroy_user_session_path : new_user_session_path, method: current_user ? :delete : :get %></li>
        </ul>
    </nav>
    <h1>GALLYWAGGER</h1>
    <p>Your go-to prediction game!</p>
    <div class="scores">
      <div class="score-block">Weekly Score: <%= @weekly_score %></div>
      <div class="score-block">Season Score: <%= @season_score %></div>
      <div class="score-block">Lifetime Score: <%= @lifetime_score %></div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/predictions/index.html.erb
<table>
  <thead>
    <tr>
      <th><%= link_to 'Game Date', predictions_path(sort: 'game_date') %></th>
      <th><%= link_to 'Teams', predictions_path(sort: 'teams') %></th>
      <th><%= link_to 'Winner', predictions_path(sort: 'winner') %></th>
      <th><%= link_to 'Predicted', predictions_path(sort: 'predicted') %></th>
      <th><%= link_to 'Level', predictions_path(sort: 'level') %></th>
      <th><%= link_to 'Points', predictions_path(sort: 'points') %></th>
    </tr>
  </thead>
  <tbody>
    <% @predictions.each do |prediction| %>
      <tr>
        <td><%= prediction.game.start_time.strftime("%Y-%m-%d %H:%M") %></td> <!-- Accessing the game date -->
        <td><%= "#{prediction.game.home_team} vs #{prediction.game.away_team}" %></td> <!-- Displaying teams -->
        <td><%= prediction.game.winning_team %></td> <!-- If there's a winner field in Game -->
        <td><%= prediction.predicted_winner %></td> <!-- The user's prediction -->
        <td><%= prediction.confidence_level %></td>
        <td><%= prediction.points_awarded %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rankings/index.html.erb
<div class="rankings-tabs">
  <button data-target="#weekly">Weekly</button>
  <button data-target="#season">Season</button>
  <button data-target="#lifetime">Lifetime</button>
</div>

<!-- Weekly Rankings Table -->
<div id="weekly" class="rankings-table">
  <table>
    <thead>
      <tr>
        <th>Rank</th>
        <th>User</th>
        <th>Score</th>
      </tr>
    </thead>
    <tbody>
      <% @weekly_rankings.each_with_index do |ranking, index| %>
        <tr class="<%= 'highlight' if ranking.highlight_current_user?(current_user) %>">
          <td><%= index + 1 %></td>
          <td><%= ranking.username %></td>
          <td><%= ranking.weekly_score %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<!-- Season Rankings Table -->
<div id="season" class="rankings-table">
  <table>
    <thead>
      <tr>
        <th>Rank</th>
        <th>User</th>
        <th>Score</th>
      </tr>
    </thead>
    <tbody>
      <% @season_rankings.each_with_index do |ranking, index| %>
        <tr class="<%= 'highlight' if ranking.highlight_current_user?(current_user) %>">
          <td><%= index + 1 %></td>
          <td><%= ranking.username %></td>
          <td><%= ranking.season_score %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<!-- Lifetime Rankings Table -->
<div id="lifetime" class="rankings-table">
  <table>
    <thead>
      <tr>
        <th>Rank</th>
        <th>User</th>
        <th>Score</th>
      </tr>
    </thead>
    <tbody>
      <% @lifetime_rankings.each_with_index do |ranking, index| %>
        <tr class="<%= 'highlight' if ranking.highlight_current_user?(current_user) %>">
          <td><%= index + 1 %></td>
          <td><%= ranking.username %></td>
          <td><%= ranking.lifetime_score %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>